import { Geist,Prata,Mali} from "next/font/google";

const pratafont = Prata({
  subsets: ["latin"],
  weight:"400"
})
const malifont = Mali({
  subsets: ["latin"],
  weight:['200', '300', '400', '500', '600', '700']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" href="favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Slicer Slider</title>
      </head>
      <body
        className={`${pratafont.className} ${malifont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
