name: Full Project FTP Deploy (Long Timeout)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout project
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3. Install and Build (for generating .next folder)
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 4. Upload everything except node_modules, git & dev files
      - name: Upload full project via FTP (no node_modules)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          local-dir: ./  # Project root
         
          exclude: |
            **/node_modules/**
            **/.git/**
            **/.gitignore
            **/.github/**
            **/.vscode/**
            **/.env
            **/README.md
            **/package-lock.json
          timeout: 3600  # 1 hour timeout (max allowed for FTP servers)
          log-level: minimal
