name: Deploy to Server (via FTP + SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3. Install and Build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4. Prepare deployment folder
      - name: Create deployment folder and zip
        run: |
          mkdir deploy
          cp -r .next package.json public deploy/
          # only copy next.config.js if it exists
          if [ -f next.config.js ]; then cp next.config.js deploy/; fi
          cd deploy
          zip -r deploy.zip .

      # 5. Upload zipped project via FTP
      - name: Upload zipped build via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/
          server-dir: /home/username/app-deploy/  # 🔁 change this to your server path
          exclude: |
            **/node_modules/**
          timeout: 600
          log-level: verbose

      # 6. SSH to server and deploy
      - name: SSH and deploy on server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/username/app-deploy
            unzip -o deploy.zip
            npm install
            pm2 delete next-app || true
            pm2 start npm --name "next-app" -- start
            pm2 save
