name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3. Install and Build
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 4. Zip build
      - name: Zip the project
        run: |
          mkdir deploy
          cp -r .next package.json public next.config.js deploy/
          cd deploy
          zip -r deploy.zip .

      # 5. Upload the zip file via FTP
      - name: Upload zipped project via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/
          server-dir: /
          exclude: |
            **/node_modules/**
          timeout: 600

      # 6. SSH in and unzip
      - name: SSH and Deploy on Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/username/app-deploy
            unzip -o deploy.zip
            npm install
            pm2 delete next-app || true
            pm2 start npm --name "next-app" -- start
            pm2 save
