name: Deploy via SSH + SCP (no FTP)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3. Install and build
      - name: Install and build
        run: |
          npm install
          npm run build

      # 4. Create deployable ZIP
      - name: Prepare ZIP for deployment
        run: |
          mkdir deploy
          cp -r .next package.json public deploy/
          if [ -f next.config.js ]; then cp next.config.js deploy/; fi
          cd deploy
          zip -r deploy.zip .

      # 5. Upload ZIP to server via SCP
      - name: Upload deploy.zip via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "deploy/deploy.zip"
          target: "/home/username/app-deploy/"  # 🔁 change this path to match your server

      # 6. SSH to server and unzip + start PM2
      - name: SSH and deploy on server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/username/app-deploy  # 🔁 make sure this matches the above
            unzip -o deploy.zip
            npm install
            pm2 delete next-app || true
            pm2 start npm --name "next-app" -- start
            pm2 save
